version: "3.9"
services:
  auto-gpt:
    image: areghoi/auto-gpt
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./work_dir/auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./work_dir/data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./work_dir/logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      - ./work_dir/ai_settings.yaml:/app/ai_settings.yaml
  redis:
    image: "redis/redis-stack-server:latest"
